alert("Say you are here")
alert("Hey, probably you skipped last one by mistake its ok")
alert("I dont really know what you are doing here")
alert("Kindly go back")
alert("You can go back by just exiting this tab")
alert("OR")
alert("I don't know just exit from this tab")
alert("Take your time")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("Why are you still here?")
alert("Isn't it frustruating?")
alert("Probably you are a hardcore person or just very patient")
alert("OR you don't have anything to do, so you are just going on")
alert("You should leave now")
alert("It was the end")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("ENDING")
alert("................")
alert("Wow, you are actually doing all this")
alert("But for what?")
alert("I guess you really want to see")
alert("But its nothing there, you will be dissapointed")
alert("Then here you go")
alert("3")
alert("2")
alert("1")
alert("Go")
alert("You really thought, I will let you see")
alert("I am you are very annoyed and bored right now")
alert("What do you think, its not going to be easy")
alert("I won't mind if you cheat by copying my code and viewing it in another tab")
alert("But all this was for you")
alert("But all this was to test you")
alert("To test your patience")
alert("Ok then, if you want, just go and cheat, but you won't be able to view it very properly")
alert("Never mind, you have alternatives")
alert("So once again, i will put in this test")
alert("Have a happy day")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("BYE")
alert("You are truly such a person, I envy you")
alert("I dont know if you will like what I have done")
alert("Its very simple, it might disappoint you")
alert("But its for testing anyways")
alert("Here you go in")
alert("3")
alert("2")
alert("1")
alert("Go")